version: 2.1

parameters:
  image-name:
    type: string
    default: 'mkroman/meta-mail_reader'

jobs:
  test:
    docker:
      - image: circleci/ruby:2.7-buster
    steps:
      - checkout
      - restore_cache:
          keys:
            - meta-mail_reader-bundle-{{ checksum "Gemfile.lock" }}
      - run:
          name: Bundle Install
          command: bundle check --path vendor/bundle || bundle install --deployment
      - save_cache:
          key: meta-mail_reader-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          command: bundle exec rspec --format documentation

  build:
    docker:
      - image: circleci/buildpack-deps:buster
    environment:
      IMAGE_NAME: << pipeline.parameters.image-name >>
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t ${IMAGE_NAME}:latest .

  release:
    docker:
      - image: circleci/buildpack-deps:buster
    environment:
      IMAGE_NAME: << pipeline.parameters.image-name >>
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Authenticate to Docker registry
          command: |
            echo "${DOCKER_PASS}" | docker login --username "${DOCKER_USER}" --password-stdin
      - run:
          name: Build Docker image
          command: |
            docker build -t ${IMAGE_NAME}:latest .
      - run:
          name: Push Docker image
          command: |
            GIT_COMMIT_ID=$(git rev-parse --short HEAD)
            docker tag "${IMAGE_NAME}:latest" "${IMAGE_NAME}:${CIRCLE_TAG}"
            docker tag "${IMAGE_NAME}:latest" "${IMAGE_NAME}:${GIT_COMMIT_ID}"
            docker push "${IMAGE_NAME}:latest"
            docker push "${IMAGE_NAME}:${CIRCLE_TAG}"
            docker push "${IMAGE_NAME}:${GIT_COMMIT_ID}"

workflows:
  version: 2

  test_and_release:
    jobs:
      - test
      - build
      - release:
          filters:
            tags:
              only: /^v.+/

          requires:
            - test
            - build
